import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/footer";
import Header from "@/components/common/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} `}
      >
        <div className="w-full ">
          {/* Header and hero section */}
          <div className="w-full">
            {/* <Header/> */}
          </div>
          {/* Main content */}
          <div>    
            {children}
          </div>

          <div className="bg-amber-300">
            {/* Footer */}
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
